apiVersion: v1
kind: Service
metadata:
  name: snarker-http-coordinator
spec:
  type: ClusterIP
  selector:
    app: snarker-http-coordinator
  ports:
  - name: tcp-daemon-rpc
    port: 8080
    targetPort: 80
